config/routes.rb
  Rails.application.routes.draw do
  root to: "homes#index"

  devise_for :users
  
  resources :afs, only: [:index, :show] do
    resources :fields, only: [:show]
  end
  resources :pfs, only: [:index, :show] do
    resources :fields, only: [:show]
  end
  resources :fields, only: [:index, :show] do
    resources :jobs, only: [:index, :show] do
      resources :jobcoms, except: [:index, :show] do
        resources :jobans, except: [:index, :show]
      end
    end
  end
  
  resources :mfs, only: [:index, :show] do
    resources :comments, except: [:index, :show] do
      resources :answers, except: [:index, :show] do
        resources :likes, only: [:create] 
      end
    end
  end
  resources :ffs, only: [:index, :show] do
    resources :ffcoms, except: [:index, :show] do
      resources :ffans, except: [:index, :show] do
        resources :ffanslikes, only: [:create]
      end
    end
  end

  # likes pour commentaire

  resources :mfs, only: [:index, :show] do
    resources :comments, except: [:index, :show] do
        resources :lcs, only: [:create] 
    end
  end
  resources :ffs, only: [:index, :show] do
    resources :ffcoms, except: [:index, :show] do
        resources :ffcomlikes, only: [:create]
    end
  end

  # likes pour commentaires et réponses de jobs
    resources :jobs, only: [:index, :show] do
      resources :jobcoms, except: [:index, :show] do
        resources :jobcomlikes, only: [:create]
      end
    end
    
    resources :jobs, only: [:index, :show] do
      resources :jobans, except: [:index, :show] do
        resources :jobanslikes, only: [:create]
      end
    end



  resources :orders, only: [:create]
  resources :users, only: [:create]
  resources :images, only:[:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places
end

app/models/af.rb
class Af < ApplicationRecord
	has_many :fields
end

app/models/answer.rb
class Answer < ApplicationRecord
#attribut
	has_many :likes
# index
	belongs_to :user
	belongs_to :mf, optional: true
	belongs_to :ff, optional: true
	belongs_to :comment, optional: true
	belongs_to :job, optional: true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	has_many :mfs
	has_many :ffs
	has_many :jobs
end

app/models/comment.rb
class Comment < ApplicationRecord
	has_many :answers
	has_many :likes
	# index
	belongs_to :mf, optional: true
	belongs_to :ff, optional: true
	belongs_to :user, optional: true
	belongs_to :job, optional: true
end

app/models/ff.rb
class Ff < ApplicationRecord
	#index
	belongs_to :field
	belongs_to :city

	# attributs
	has_many :orders
	has_many :users, through: :orders
	has_many :comments
	has_many :answers
	has_many :likes

end

app/models/field.rb
class Field < ApplicationRecord
	belongs_to :pf
	belongs_to :af
#for each field
	has_many :mfs
	has_many :ffs
	has_many :jobs
end

app/models/job.rb
class Job < ApplicationRecord
#attributs
	has_many :comments
	has_many :answers
	has_many :likes
#index
	belongs_to :city
	belongs_to :field
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :comment, optional: true
	belongs_to :answer, optional: true
	belongs_to :mf, optional: true
	belongs_to :ff, optional: true
	belongs_to :job, optional: true
	belongs_to :user
end

app/models/mf.rb
class Mf < ApplicationRecord
#index
	belongs_to :field
	belongs_to :city
#attributs
	has_many :orders
	has_many :users, through: :orders
	has_many :comments
	has_many :answers
	has_many :likes

end

app/models/order.rb
class Order < ApplicationRecord
#index
	belongs_to :user
	belongs_to :mf
	belongs_to :ff
#attributs	
end

app/models/pf.rb
class Pf < ApplicationRecord
	has_many :fields
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

# jointure pour user
# ETQ index
belongs_to :city, optional: true
#ETQ attributs
has_many :comments
has_many :answers
has_many :likes

# Relation N-N entre user et ff, mf
has_many :orders
has_many :mfs, through: :orders
has_many :ffs, through: :orders

end

app/controllers/ffs_controller.rb
class FfsController < ApplicationController
  def index
  end

  def show
    @ff = Ff.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/afs_helper.rb
module AfsHelper
end

app/helpers/ffans_helper.rb
module FfansHelper
end

app/helpers/ffs_helper.rb
module FfsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/lcs_helper.rb
module LcsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mfs_helper.rb
module MfsHelper
end

app/helpers/pfs_helper.rb
module PfsHelper
end

app/views/ffs/create.html.erb
<h1>Ffs#create</h1>
<p>Find me in app/views/ffs/create.html.erb</p>

app/views/ffs/destroy.html.erb
<h1>Ffs#destroy</h1>
<p>Find me in app/views/ffs/destroy.html.erb</p>

app/views/ffs/edit.html.erb
<h1>Ffs#edit</h1>
<p>Find me in app/views/ffs/edit.html.erb</p>

app/views/ffs/index.html.erb
<h1>Ffs#index</h1>
<p>Find me in app/views/ffs/index.html.erb</p>

app/views/ffs/new.html.erb
<h1>Ffs#new</h1>
<p>Find me in app/views/ffs/new.html.erb</p>

app/views/ffs/show.html.erb
<div>
	
	<h1><%=@ff.title%></h1><br>
	<p><%=@ff.description%></p><br>
	<ul>
		<li>
			Contact: <%=@ff.contact%>
		</li>
		<li>
			e-mail: <%=@ff.email%>
		</li>
		<li>
			Durée de formation: <%=@ff.duration%>
		</li>
		<li>
			Prix de formation: <%=@ff.price%>
		</li>
	</ul>
<!--video et image sur cette formation-->
	<ul>
		<li>
			Videos
		</li>		
	</ul>
</div>
<!--ici les commentaires-->
<div>
		<p>Laisser des commentaires(<small><%=@ff.comments.length%> , <%=@ff.answers.length%> réponses </small>)</p>
		<%=form_with url: ff_ffcoms_path(@ff.id), action:"create", method: :post, local: true do |f|%>
		<%=f.text_area :body, placeholder:"Votre commentaire ici ..."%>
		<%=f.submit "Envoyer"%>
		<%end%>
		<%@ff.comments.each do |comment|%>
			<p>	
				<%=comment.body%> <small>(<%=comment.answers.length%> réponse(s))</small><br>
				<small>
					<i><%=comment.user.first_name%> le <%=comment.created_at%></i><br>
					<%=link_to "Editer", edit_ff_ffcom_path(@ff.id, comment.id)%>
					<%=link_to "suprimer",   ff_ffcom_path(@ff.id, comment.id), method: :delete, data: { confirm: 'Are you sure?' } %>
					<%=link_to "J'aime(#{comment.likes.length} likes)", ff_ffcom_ffcomlikes_path(@ff.id, comment.id), action: "create", method: :post%>
				</small>
			</p>
			<small>
				<%=link_to "Répondre à ce commentaire", new_ff_ffcom_ffan_path(@ff.id, comment.id)%>
			</small>
			<!--liste des réponses-->
			<%comment.answers.each do |answer|%>
				<ul>
					<li>
						<%=answer.body%> 
						<small>
							<i>Réponse de <%=answer.user.first_name%></i><br>
							<%=link_to "Editer", edit_ff_ffcom_ffan_path(@ff.id, comment.id, answer.id)%>
							<%=link_to "suprimer",   ff_ffcom_ffan_path(@ff.id, comment.id, answer.id), method: :delete, data: { confirm: 'Are you sure?' } %>
							<%=link_to "J'aime(#{answer.likes.length} likes)",  ff_ffcom_ffan_ffanslikes_path(@ff.id, comment.id, answer.id), action: "create", method: :post%>
						</small>
					</li>
				</ul>
			<%end%>
		<%end%>		
</div>

app/views/ffs/update.html.erb
<h1>Ffs#update</h1>
<p>Find me in app/views/ffs/update.html.erb</p>