config/routes.rb
  Rails.application.routes.draw do
  root to: "homes#index"

  devise_for :users
  
  resources :afs, only: [:index, :show] do
    resources :fields, only: [:show]
  end
  resources :pfs, only: [:index, :show] do
    resources :fields, only: [:show]
  end
  resources :fields, only: [:index, :show] do
    resources :jobs, only: [:index, :show] do
      resources :jobcoms, except: [:index, :show] do
        resources :jobans, except: [:index, :show]
      end
    end
  end
  
  resources :mfs, only: [:index, :show] do
    resources :comments, except: [:index, :show] do
      resources :answers, except: [:index, :show] do
        resources :likes, only: [:create] 
      end
    end
  end
  resources :ffs, only: [:index, :show] do
    resources :ffcoms, except: [:index, :show] do
      resources :ffans, except: [:index, :show] do
        resources :ffanslikes, only: [:create]
      end
    end
  end

  # likes pour commentaire

  resources :mfs, only: [:index, :show] do
    resources :comments, except: [:index, :show] do
        resources :lcs, only: [:create] 
    end
  end
  resources :ffs, only: [:index, :show] do
    resources :ffcoms, except: [:index, :show] do
        resources :ffcomlikes, only: [:create]
    end
  end

  # likes pour commentaires et réponses de jobs
    resources :jobs, only: [:index, :show] do
      resources :jobcoms, except: [:index, :show] do
        resources :jobcomlikes, only: [:create]
      end
    end
    
    resources :jobs, only: [:index, :show] do
      resources :jobans, except: [:index, :show] do
        resources :jobanslikes, only: [:create]
      end
    end



  resources :orders, only: [:create]
  resources :users, only: [:create]
  resources :images, only:[:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places
end

app/models/af.rb
class Af < ApplicationRecord
	has_many :fields
end

app/models/answer.rb
class Answer < ApplicationRecord
#attribut
	has_many :likes
# index
	belongs_to :user
	belongs_to :mf, optional: true
	belongs_to :ff, optional: true
	belongs_to :comment, optional: true
	belongs_to :job, optional: true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	has_many :mfs
	has_many :ffs
	has_many :jobs
end

app/models/comment.rb
class Comment < ApplicationRecord
	has_many :answers
	has_many :likes
	# index
	belongs_to :mf, optional: true
	belongs_to :ff, optional: true
	belongs_to :user, optional: true
	belongs_to :job, optional: true
end

app/models/ff.rb
class Ff < ApplicationRecord
	#index
	belongs_to :field
	belongs_to :city

	# attributs
	has_many :orders
	has_many :users, through: :orders
	has_many :comments
	has_many :answers
	has_many :likes

end

app/models/field.rb
class Field < ApplicationRecord
	belongs_to :pf
	belongs_to :af
#for each field
	has_many :mfs
	has_many :ffs
	has_many :jobs
end

app/models/job.rb
class Job < ApplicationRecord
#attributs
	has_many :comments
	has_many :answers
	has_many :likes
#index
	belongs_to :city
	belongs_to :field
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :comment, optional: true
	belongs_to :answer, optional: true
	belongs_to :mf, optional: true
	belongs_to :ff, optional: true
	belongs_to :job, optional: true
	belongs_to :user
end

app/models/mf.rb
class Mf < ApplicationRecord
#index
	belongs_to :field
	belongs_to :city
#attributs
	has_many :orders
	has_many :users, through: :orders
	has_many :comments
	has_many :answers
	has_many :likes

end

app/models/order.rb
class Order < ApplicationRecord
#index
	belongs_to :user
	belongs_to :mf
	belongs_to :ff
#attributs	
end

app/models/pf.rb
class Pf < ApplicationRecord
	has_many :fields
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

# jointure pour user
# ETQ index
belongs_to :city, optional: true
#ETQ attributs
has_many :comments
has_many :answers
has_many :likes

# Relation N-N entre user et ff, mf
has_many :orders
has_many :mfs, through: :orders
has_many :ffs, through: :orders

end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  def index
    
  end

  def show
    @field = Field.find(params[:id])
    field = Field.find(params[:id])
    @mfs = field.mfs
    @ffs = field.ffs
  end

  def edit
  end

  def update
  end

  def new
  end

  def createdestroy
  end
end

app/helpers/afs_helper.rb
module AfsHelper
end

app/helpers/ffans_helper.rb
module FfansHelper
end

app/helpers/ffs_helper.rb
module FfsHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/lcs_helper.rb
module LcsHelper
end

app/helpers/mfs_helper.rb
module MfsHelper
end

app/helpers/pfs_helper.rb
module PfsHelper
end

app/views/fields/createdestroy.html.erb
<h1>Fields#createdestroy</h1>
<p>Find me in app/views/fields/createdestroy.html.erb</p>

app/views/fields/edit.html.erb
<h1>Fields#edit</h1>
<p>Find me in app/views/fields/edit.html.erb</p>

app/views/fields/index.html.erb
<div>
	<h1>Offre d'emploi</h1>
	<div>
		<h2> Les emplois par domaine</h2>
		<ul>
			<%jobs.each do |field|%>
			<li>
				<h2>
					<%=link_to "Emplois sur #{field.title}", field_jobs_path(field.id)%>				
				</h2>
				<p><%=field.description%></p>
			</li>
			<%end%>
		</ul>
	</div> <br><br>
		
	<div>
		<h2> Les emplois par entreprise </h2>
		<ul>
			<%buisness.each do |buisness|%>
			<li>
				<h2>
					<%=link_to " Emplois chez #{buisness}"%>				
				</h2>
			</li>
			<%end%>
		</ul>
	</div> <br><br>

	<div>
		<h2> Les emplois par Ville </h2>
		<ul>
			<%city_jobs.each do |city|%>
			<li>
				<h2>
					<%=link_to "Emplois à #{city.name}"%>				
				</h2>
			</li>
			<%end%>
		</ul>
	</div>

</div>

app/views/fields/new.html.erb
<h1>Fields#new</h1>
<p>Find me in app/views/fields/new.html.erb</p>

app/views/fields/show.html.erb
<div>
	<h1><%=@field.title%></h1><br>
	<p><%=@field.description%></p>
	<ul>
		<li>
			<%=link_to "Les formations continues"%>
			<p>Petite description préliminaire sur les formations continues</p><br>
			<ul>
				<%@ffs.each do |ff|%>
				<li>
					<%=link_to ff.title, ff_path(ff.id)%>
				</li>
				<%end%>
			</ul>
		</li>
		<li>
			<%=link_to "Les formations modulaires"%>
			<p>Petite description préliminaire sur les formations modulaires</p><br>
			<ul>
				<%@mfs.each do |mf|%>
				<li>
					<%=link_to mf.title, mf_path(mf.id)%>
				</li>
				<%end%>
			</ul>
		</li>
	</ul>
</div>

app/views/fields/update.html.erb
<h1>Fields#update</h1>
<p>Find me in app/views/fields/update.html.erb</p>