config/routes.rb
  Rails.application.routes.draw do
  root to: "homes#index"

  devise_for :users
  
  resources :afs, only: [:index, :show] do
    resources :fields, only: [:show]
  end
  resources :pfs, only: [:index, :show] do
    resources :fields, only: [:show]
  end
  resources :fields, only: [:index, :show] do
    resources :jobs, only: [:index, :show] do
      resources :jobcoms, except: [:index, :show] do
        resources :jobans, except: [:index, :show]
      end
    end
  end
  
  resources :mfs, only: [:index, :show] do
    resources :comments, except: [:index, :show] do
      resources :answers, except: [:index, :show] do
        resources :likes, only: [:create] 
      end
    end
  end
  resources :ffs, only: [:index, :show] do
    resources :ffcoms, except: [:index, :show] do
      resources :ffans, except: [:index, :show] do
        resources :ffanslikes, only: [:create]
      end
    end
  end

  # likes pour commentaire

  resources :mfs, only: [:index, :show] do
    resources :comments, except: [:index, :show] do
        resources :lcs, only: [:create] 
    end
  end
  resources :ffs, only: [:index, :show] do
    resources :ffcoms, except: [:index, :show] do
        resources :ffcomlikes, only: [:create]
    end
  end

  # likes pour commentaires et réponses de jobs
    resources :jobs, only: [:index, :show] do
      resources :jobcoms, except: [:index, :show] do
        resources :jobcomlikes, only: [:create]
      end
    end
    
    resources :jobs, only: [:index, :show] do
      resources :jobans, except: [:index, :show] do
        resources :jobanslikes, only: [:create]
      end
    end



  resources :orders, only: [:create]
  resources :users, only: [:create]
  resources :images, only:[:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places
end

app/models/af.rb
class Af < ApplicationRecord
	has_many :fields
end

app/models/answer.rb
class Answer < ApplicationRecord
#attribut
	has_many :likes
# index
	belongs_to :user
	belongs_to :mf, optional: true
	belongs_to :ff, optional: true
	belongs_to :comment, optional: true
	belongs_to :job, optional: true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
	has_many :mfs
	has_many :ffs
	has_many :jobs
end

app/models/comment.rb
class Comment < ApplicationRecord
	has_many :answers
	has_many :likes
	# index
	belongs_to :mf, optional: true
	belongs_to :ff, optional: true
	belongs_to :user, optional: true
	belongs_to :job, optional: true
end

app/models/ff.rb
class Ff < ApplicationRecord
	#index
	belongs_to :field
	belongs_to :city

	# attributs
	has_many :orders
	has_many :users, through: :orders
	has_many :comments
	has_many :answers
	has_many :likes

end

app/models/field.rb
class Field < ApplicationRecord
	belongs_to :pf
	belongs_to :af
#for each field
	has_many :mfs
	has_many :ffs
	has_many :jobs
end

app/models/job.rb
class Job < ApplicationRecord
#attributs
	has_many :comments
	has_many :answers
	has_many :likes
#index
	belongs_to :city
	belongs_to :field
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :comment, optional: true
	belongs_to :answer, optional: true
	belongs_to :mf, optional: true
	belongs_to :ff, optional: true
	belongs_to :job, optional: true
	belongs_to :user
end

app/models/mf.rb
class Mf < ApplicationRecord
#index
	belongs_to :field
	belongs_to :city
#attributs
	has_many :orders
	has_many :users, through: :orders
	has_many :comments
	has_many :answers
	has_many :likes

end

app/models/order.rb
class Order < ApplicationRecord
#index
	belongs_to :user
	belongs_to :mf
	belongs_to :ff
#attributs	
end

app/models/pf.rb
class Pf < ApplicationRecord
	has_many :fields
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

# jointure pour user
# ETQ index
belongs_to :city, optional: true
#ETQ attributs
has_many :comments
has_many :answers
has_many :likes

# Relation N-N entre user et ff, mf
has_many :orders
has_many :mfs, through: :orders
has_many :ffs, through: :orders

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
    puts"#{Rails.application.credentials.key}"
    puts"#{@place.latitude}"
    puts"#{@place.longitude}"

  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :latitude, :longitude)
    end
end

app/helpers/afs_helper.rb
module AfsHelper
end

app/helpers/ffans_helper.rb
module FfansHelper
end

app/helpers/ffs_helper.rb
module FfsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/lcs_helper.rb
module LcsHelper
end

app/helpers/mfs_helper.rb
module MfsHelper
end

app/helpers/pfs_helper.rb
module PfsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <style>
    body{
      background-image: url(http://www.theverylittlewar.com/images/fondmenu.jpg);
    }
  </style>
</head>
<body>
<h1>Modification</h1>

<%= render 'form', place: @place %>

<%= link_to 'Afficher', @place %> |
<%= link_to 'Retour', places_path %>
</body>

app/views/places/index.html.erb
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <style>
    body{
      background-image: url(http://www.theverylittlewar.com/images/fondmenu.jpg);
    }
    .btn-secondary{
      text-align: center;
    }
    
  </style>
</head>
<body>
<p id="notice"><%= notice %></p>

  <h1 style="color: white;">Pla<span style="color:green;">ces</span></h1>
  <a class="logs btn btn-secondary" href="<%= new_place_path%>" role="button">Créer</a>

  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th>Lieu</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @places.each do |place| %>
        <tr>
          <td><%= place.name %></td>
          <td><%= place.latitude %></td>
          <td><%= place.longitude %></td>
          <td><%= link_to 'Afficher', place %></td>
          <td><%= link_to 'Editer', edit_place_path(place) %></td>
          <td><%= link_to 'Supprimer', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  
  
</body>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <style>
    body{
      background-image: url(http://www.theverylittlewar.com/images/fondmenu.jpg);
    }
  </style>
</head>
<body>
<% provide :head_tags do %>
    <script>
    document.addEventListener("DOMContentLoaded", function(){
        initMap(<%=@place.latitude%>, <%=@place.longitude%>)
    });
    </script>
<% end %>
	
<p style="color: white;">
  <strong>Name:</strong>
  <%= @place.name %>
</p>
<p>
<div id="map" style="width:100%;height:500px"></div>

<script>
function myMap() {
  var mapCanvas = document.getElementById("map");
  var mapOptions = {
    center: new google.maps.LatLng(51.508742, -0.120850),
    zoom: 5
  };
  var map = new google.maps.Map(mapCanvas, mapOptions);
}
</script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAgAXF9oCID7Osw3tBeZufKg1aQjByUZyY&callback=myMap"
  type="text/javascript"></script>
<p style="color: gray;">
<%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=17&size=400x300&center=#{@place.latitude},#{@place.longitude}&key=#{Rails.application.credentials.key}", alt: "Map" %>
</p>
<%= link_to 'Editer', edit_place_path(@place) %> 
<%= link_to 'Retour', places_path %>
</body>